### ISSUE TITLE
Pull Request not a Pull Request and Access Issues

### ISSUE THREAD

**Issue by ChristinaB** [waterhackweek/learning-resources#5]
@emiliom 
To follow up from our call - the files that are here are what I had updated, but the placeholders for HydroShare and Binder etc. did not get updated (yet) by collaborators.   So I did not run the code to reload the website with this version (yet), but now I will fork this to my personal login and do a PR for you, unless I get other instructions from you.

**Comment by emiliom** [comment]
@ChristinaB Yes, please push your local changes to your personal fork and issue a PR from there. Ping me on the PR, but don't merge it. I'll take a look and do the merging myself. BTW, I've checked and I do already have "admin" permissions, so I'm good to go on the permissions front.

Please don't run the code to reload the website. I want to reconcile your PR first, then roll out the automatic web site renderer so that manually reloading the web site will no longer be necessary (or recommended!).

**Comment by emiliom** [comment]
Regarding this:
>  the placeholders for HydroShare and Binder etc. did not get updated (yet) by collaborators.

Just adding a reference to #3, which seems to be a related issue

**Comment by emiliom** [comment]
I've made a lot of progress on my end. Please submit your PR ASAP so we can get this puppy out and ready for incremental edits!
